/**
 * Packs the Python runtime into the single expression the extension evaluates
 * inside the debuggee.
 *
 * Output is `src/generated/bootstrap.ts`, which is generated rather than
 * committed so the Python sources stay the single source of truth. The mirror
 * of this logic lives in `packages/runtime/tests/conftest.py`, which lets the
 * Python test suite exercise the loader without depending on the Node build.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateSync } from "node:zlib";

const here = dirname(fileURLToPath(import.meta.url));
const extensionRoot = resolve(here, "..");
const runtimeRoot = resolve(extensionRoot, "..", "runtime");
const sourceRoot = join(runtimeRoot, "src");
const packageRoot = join(sourceRoot, "_pdv");
const loaderPath = join(runtimeRoot, "bootstrap", "loader.py");
const outputPath = join(extensionRoot, "src", "generated", "bootstrap.ts");

function collectPythonFiles(directory) {
  const found = [];
  for (const entry of readdirSync(directory).sort()) {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) {
      found.push(...collectPythonFiles(full));
    } else if (entry.endsWith(".py")) {
      found.push(full);
    }
  }
  return found;
}

/** Map module name -> [source, isPackage], the shape the loader's finder expects. */
function collectSources() {
  const sources = {};
  for (const file of collectPythonFiles(packageRoot)) {
    const parts = relative(sourceRoot, file).replace(/\.py$/, "").split(/[/\\]/);
    const isPackage = parts[parts.length - 1] === "__init__";
    const moduleName = (isPackage ? parts.slice(0, -1) : parts).join(".");
    sources[moduleName] = [readFileSync(file, "utf8"), isPackage];
  }
  return sources;
}

function readRuntimeVersion() {
  const source = readFileSync(join(packageRoot, "version.py"), "utf8");
  const match = source.match(/^RUNTIME_VERSION\s*=\s*"([^"]+)"/m);
  if (!match) {
    throw new Error("RUNTIME_VERSION not found in version.py");
  }
  return match[1];
}

function readProtocolVersion() {
  const source = readFileSync(join(packageRoot, "version.py"), "utf8");
  const match = source.match(/^PROTOCOL_VERSION\s*=\s*(\d+)/m);
  if (!match) {
    throw new Error("PROTOCOL_VERSION not found in version.py");
  }
  return Number(match[1]);
}

const compress = (text) => deflateSync(Buffer.from(text, "utf8"), { level: 9 }).toString("base64");

const runtimeVersion = readRuntimeVersion();
const protocolVersion = readProtocolVersion();

const sources = JSON.stringify(collectSources());

/**
 * Identity of the code being injected, not of the release.
 *
 * A debug session installs the runtime once and keeps it. Keying that on a
 * hand-maintained version string means an edited runtime never reaches a
 * session that is already running -- the new code is simply skipped, and the
 * symptom is a feature that silently does nothing until the session is
 * restarted. Hashing the sources makes any edit replace the installed copy.
 */
const runtimeBuild = `${runtimeVersion}+${createHash("sha256").update(sources).digest("hex").slice(0, 12)}`;

const loader = readFileSync(loaderPath, "utf8")
  .replace("@@SOURCES@@", compress(sources))
  .replace("@@BUILD@@", runtimeBuild);

// The trailing `{}` gives exec its own globals so the loader's names never
// reach the frame the user is paused in. See packages/runtime/bootstrap/loader.py.
const expression = `exec(__import__("zlib").decompress(__import__("base64").b64decode("${compress(loader)}")).decode("utf-8"), {})`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/pack-runtime.mjs. Do not edit.
// Source of truth: packages/runtime/

export const RUNTIME_VERSION = ${JSON.stringify(runtimeVersion)};

/** Version plus a hash of the packed sources; changes whenever the code does. */
export const RUNTIME_BUILD = ${JSON.stringify(runtimeBuild)};
export const RUNTIME_PROTOCOL_VERSION = ${protocolVersion};

/** Single expression that installs the runtime into the debuggee's sys.modules. */
export const BOOTSTRAP_EXPRESSION = ${JSON.stringify(expression)};
`,
  "utf8",
);

const kb = (expression.length / 1024).toFixed(1);
console.log(`pack-runtime: ${runtimeBuild}, bootstrap expression ${kb} KB`);
